### PR TITLE
Tracked Maps and Sets

### PR DESCRIPTION
**Pull request by pzuraq**
[Rendered](https://github.com/emberjs/rfcs/blob/tracked-maps-and-sets/text/0577-tracked-maps-and-sets.md)

### CODE REVIEW

**Comment by Gaurav0** [comment]
I'd prefer this to be in a separate package rather than part of `@glimmer/tracking` so that we can tree shake it.

**Comment by NullVoxPopuli** [comment]
> I'd prefer this to be in a separate package rather than part of @glimmer/tracking so that we can tree shake it.

tree shaking can work on multiple imports of the same package

**Comment by Gaurav0** [comment]
> > I'd prefer this to be in a separate package rather than part of @glimmer/tracking so that we can tree shake it.
> 
> tree shaking can work on multiple imports of the same package

I am unaware of how this works. Right now we can only do "manual tree shaking" in ember-cli; i.e. not load a package. While Embroider may change this someday, we must work with what we have now. Once Ember core is property separated into *real* separate packages, with today's ember-cli we will be able to only load or not load the entire package.

**Comment by pzuraq** [comment]
This would not be implemented as a separate package either way, so manual treeshaking would not be possible. We should build for automatic treeshaking.

**Comment by Gaurav0** [comment]
Sorry, why not? It is in a separate addon now.

**Comment by pzuraq** [comment]
`@glimmer/tracking` is not a separate addon. You can install the addon for types, but it is still provided by `ember-source`.

**Comment by Gaurav0** [comment]
Yes. I would like this to be separate from `@glimmer/tracking`

**Comment by NullVoxPopuli** [comment]
@Gaurav0 I think we have too many imports as is.

**Comment by Gaurav0** [comment]
@NullVoxPopuli Why? The imports went through the RFC process and were agreed to by the community.

**Comment by NullVoxPopuli** [comment]
@Gaurav0 I just mean that I feel like we have too many imports as is -- not that there is anything we can do about it -- all the imports make sense. 
Adding more tracked utilities should be on `@glimmer/tracking`, as the RFC states, because they are very related. Splitting that up doesn't make sense to me.  
I understand the desire to have tree shaking, but we need to design for the future, and not hold ourselves back with existing tech... idk if that makes sense. I need to eat. lol

**Comment by pzuraq** [comment]
@Gaurav0 for pragmatic purposes, this would not be implemented as a separate addon for the time being, which is my overall point.

**Comment by Gaurav0** [comment]
> Adding more tracked utilities should be on @glimmer/tracking, as the RFC states, because they are very related. Splitting that up doesn't make sense to me.

IMHO, I disagree. The `tracked` function and decorator is likely to be much more widely used than any additional utilities. This is similar to how `computed` is on `@ember/object` and macros are on `@ember/object/computed`.

The only additional thing I think should be added to this import

**Comment by sandstrom** [comment]
Good suggestion, I really like this idea.

**However, I think designing something proxy-based would be much better and [browser support is excellent](https://caniuse.com/#search=proxy). Let's come up with something modern, with longer shelf-life.**

IE 11 is in rapid decline and only have a few percentage points of usage these days.

Many large software companies has already stopped supporting it, for example:

- [Atlassian has dropped support for IE 11](https://blog.developer.atlassian.com/retiring-ie11-support-for-atlassian-cloud-server-and-data-center-products/)

- [Zendesk has dropped IE 11 support](https://support.zendesk.com/hc/en-us/articles/360002084367-Removal-of-support-for-Internet-Explorer-11)

- [Qlik View let go of IE 11 too](https://support.qlik.com/articles/000079718)

- We're not a huge company, but we dropped support for IE11 and none of our ~1000 customers complained. When we checked usage logs, for the few companies that still had IE11 usage 100% of them had other browsers installed on their machines already, and somewhere around 50-90% of their employees already used another browser.

The days where IE11 was the only browser installed on a computer are long gone.

Ember should drop IE 11 support and focus time on using the modern JS toolset to provide a nice framework. Any Ember user that need to extend support a while longer, e.g. end of 2020, could simply linger on an Ember LTS a while longer. It doesn't need to hold back new framework development.

*Regarding the performance drawback with proxies, I don't think it would be a big problem under most real-world scenarios.*

**Comment by pzuraq** [comment]
@sandstrom these classes do not require a proxy to wrap transparently, since all access is done through methods, unlike arrays. Ultimately, the exact implementation should likely be whatever is most performant, and whether or not that is a subclass or a proxy should be an implementation detail.

**Comment by runspired** [comment]
Would these tracked classes be iterable by {{#each ...}} in a template or would that require wrapping in a Proxy (and dropping IE11 support)?

If yes, can we expose the underlying mechanism so that libraries like EmberData can provide custom iterables without the Proxy wrapper requirement?

**Comment by pzuraq** [comment]
> Would these tracked classes be iterable by {{#each ...}} in a template or would that require wrapping in a Proxy (and dropping IE11 support)?

A proxy is not necessary for this either way, and they should be iterable as is.

> If yes, can we expose the underlying mechanism so that libraries like EmberData can provide custom iterables without the Proxy wrapper requirement?

Yes, but I believe that should be a separate RFC specifically dedicated to outlining our support of native iterables. I also think that, because native iterables rely on Symbol, we will still need to wait for IE11 support to be fully dropped before we can deprecate alternatives to native iterables, but we can introduce support immediately in the meantime.

**Comment by NullVoxPopuli** [comment]
IE11 is now dropped, so what's left for this RFC? 
It'd be great to have more of the tracked-toolbox family of stuff built-in :D

**Comment by wagenet** [comment]
I believe this should be closed with the same rationale as https://github.com/emberjs/rfcs/pull/569#issuecomment-1193163334. If I'm mistaken, please let me know and we can work to get this moving again.

**Pull request closed without merging**
