### PR TITLE
Unify ember and glimmer(vm) repos

### PR DESCRIPTION
**Pull request by NullVoxPopuli**

### CODE REVIEW

**Comment by ef4** [comment]
This seems uncontroversial to me and I don't think it would cause a public API change that would require an RFC.

**Comment by ef4** [comment]
(Also not just glimmer-vs, but also the parts of glimmer.js that we use, like `@glimmer/component`.)

**Comment by ef4** [comment]
Closing since we think we can just do this without an RFC as it won't touch public API.

**Comment by kategengler** [comment]
Closing per @ef4's comment.

**Comment by ef4** [comment]
Getting pretty close on the prerequisites for this. Both are pnpm monorepos and I’m working to land a switch to rollup+vite in ember-source so they’ll both be the same in that respect as well.

**Pull request closed without merging**
