### PR TITLE
Add a workflow to open a PR to the next stage when the stage of an RFC has been updated

### PR DESCRIPTION
**Pull request by kategengler**
## TODO
- [x] Create a github user with only access to `emberjs/rfcs`. Get a personal access token with scope 'repo' and add to the repo's secrets under `PERSONAL_ACCESS_TOKEN`. This is required so that the opened PRs will trigger the regular github actions.
- [x] Update the workflow to use a released version of embers/rfcs-tooling once https://github.com/emberjs/rfcs-tooling/pull/9 is merged
- [ ] After merging, make checks for newly opened RFCs required. They will pass on PRs that do not add an RFC.

## Advance RFC workflow 

- Fails if more than one RFC has been updated in a single push
- Uses templates in .github/PULL_REQUEST_TEMPLATE for the body of the
  opened RFCs, with substitution of specific variables
- Sets labels on the new PR
- Updates the newly opened PR with a commit that adds the the link to
  the PR to the metadata

### Example PRs
- Advance to Ready for Release https://github.com/kategengler/playground-ghas/pull/107
- Advance to Released https://github.com/kategengler/playground-ghas/pull/108
- Advance to Recommended https://github.com/kategengler/playground-ghas/pull/109

## Newly opened RFC workflow

- Checks filename matches PR number
- Ensures Stage in frontmatter is 'accepted' before merge
- Ensures label 'S-Exploring' has been added before merge
- Ensures the PR is not labeled both 'S-Exploring' and 'S-Proposed'
- Ensures only one RFC is added in a PR
- Checks prs.accepted is correct URL

### Example
 - Adding a new RFC https://github.com/kategengler/playground-ghas/pull/106 (See checks)
 
## Label New RFC workflow

- Adds `S-Proposed` label to newly opened PRs that add an RFC

## Triggering open advancement PR

This is a workflow triggered by workflow_dispatch, either manually or through the REST API. Given an input `rfc-path` it will determine the next stage, if any, from that RFC and open a PR to advance, if necessary. We can use this workflow + the REST API to open advancement PRs for existing RFCs that are incomplete. Before we start merging RFCs with stages, we can safely run this workflow for all existing RFCs to open the advancement PRs in bulk.

### CODE REVIEW

**Review by wagenet — APPROVED** [review]
Thanks! I will admit that I did not read all of the code. Let me know if you think it needs more careful review.

**Comment by kategengler** [comment]
I think it's fine. There are probably better ways to do some of it, but it works and should be relatively maintainable 🤞

**Comment by kategengler** [comment]
Created user @emberjs-rfcs-bot for the token

**Review by wagenet — APPROVED** [review]

**Review by wagenet — APPROVED** [review]
I did not carefully review every line, but the overall setup looks good.

**Pull request merged**
