### PR TITLE
Service methods and method injection

### PR DESCRIPTION
**Pull request by tim-evans**
[Rendered](https://github.com/tim-evans/rfcs/blob/master/text/0000-service-methods.md)

This RFC is an evolution of https://github.com/emberjs/rfcs/pull/71 that piggy backs on Ember Services.
This is implemented as an addon: https://github.com/tim-evans/ember-service-methods

### CODE REVIEW

**Comment by tim-evans** [comment]
I think I'm going to close this due to inactivity.

**Comment by DingoEatingFuzz** [comment]
As far as code management, we use modules for these types of functions. You don't get DI that way, but we have gotten away with mocking services and using Pretender for testing.

**Comment by tim-evans** [comment]
@DingoEatingFuzz yeah, I was using those as well for a bit of code management as well, but it became a mess when the store was suddenly required.

I have a bunch of examples in this folder for a variety of service methods:

https://github.com/tim-evans/queertangoclub/tree/master/app/services

**Comment by tim-evans** [comment]
Closing due to inactivity :)

**Pull request closed without merging**
