### PR TITLE
WeakMap RFC

### PR DESCRIPTION
**Pull request by stefanpenner**
[rendered](https://github.com/emberjs/rfcs/blob/weakmap/text/0066-template.md)

### CODE REVIEW

**Comment by mixonic** [comment]
@stefanpenner This suggests that the Ember WeakMap would not support map -> key weakness. Correct?

If so, `destroy` on the weak map would still remove the data for all current members from memory?

**Comment by stefanpenner** [comment]
Destroying the weakmap itself would have no affect. The data would just become inaccessible and require the keys be reclaimed before

**Comment by stefanpenner** [comment]
In this case the WM is basically just a way to store private state on an object without polluting

**Comment by mixonic** [comment]
"Motivation" should likely include the specific Ember features this would be used for. To quote Stef via chat:

* Fixing computed sort nicely
* Potential future feature of runtime DK for cp

There are some addons that would use this:

* ember-state-service
* ember-cp-validations

Though those could also consume WeakMap as a stand-alone library instead. The stand-alone version would be dependent on Ember `meta` however, which would definitely be reaching into something private. Seems like it should be mentioned under "Alternatives" (not that I'm advocating for this alternative).

**Comment by stefanpenner** [comment]
Actually it isn't that meta is created out of band that is the problem. We can trigger its creation from userland. The issue is more of shaping. We can't ensure meta shapes correctly with this new slot. Unless we can insert the slot in the constructor of meta.

In theory run times should be able to adapt to afew dynamic slots added. In reality, we blow our budget of such flexibility far to easily.

We will publish a polyfil addon, so older code can use it. Unfortunately that addon will be stuck causing meta to have different slots

**Comment by jasonmit** [comment]
@stefanpenner based on the WeakMap spec, `delete` returns a boolean on whether or not the delete found anything.  In your proposal, it returns an instance of the weakmap.  Just curious if intentional or does the RFC need to be updated.

Related: https://github.com/thoov/ember-weakmap/pull/3

**Comment by stefanpenner** [comment]
we should follow the spec https://tc39.github.io/ecma262/#sec-weakmap.prototype.delete so returning true/false

**Comment by stefanpenner** [comment]
looks like the one in ember does this: https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/weak_map.js#L89-L101

**Comment by stefanpenner** [comment]
This RFC is still required to eventually make it public, as i believe the built-in weakmap is still private.

**Comment by mmun** [comment]
Looks good :+1:

**Comment by stefanpenner** [comment]
next step: https://github.com/emberjs/ember.js/issues/13668

**Pull request merged**
