### PR TITLE
Advance RFC #0617 to Stage Ready for Release

### PR DESCRIPTION
**Pull request by wagenet**
# Advance #0617 to the [Ready For Release Stage](https://github.com/emberjs/rfcs#ready-for-release)

## Summary 

[RFC-617](https://rfcs.emberjs.com/id/0617-rfc-stages) has been Accepted but remains mostly unimplemented. Since it details how we should implement Staged RFCs, it should, itself, be the first to go through the process.

This pull request is advancing the RFC to the [Ready For Release Stage](https://github.com/emberjs/rfcs#ready-for-release).

- PR to Accepted Stage: #0617 

**An FCP is required before merging this PR to advance.**

<details>
  <summary>Ready for Release Stage Description</summary>
This stage is complete when the implementation is complete according to plan 
outlined in the RFC, and is in harmony with any changes in Ember that have 
occurred since the RFC was first written. This includes any necessary learning 
materials. At this stage, features or deprecations may be available for use 
behind a feature flag, or with an optional package, etc.

For codebase changes, there are no open questions that are anticipated to 
require breaking changes; the Ember team is ready to commit to the stability of 
any interfaces exposed by the current implementation of the feature.

This stage should include a list of criteria for determining when the proposal can be considered Recommended after being Released.

An FCP is required to move into this stage.

Each Ember core team will be requested as a reviewer on the PR to move into this stage. A representative of each team adds a review. If a team does not respond to the request, and after the conclusion of the FCP, it is assumed that the release may proceed.
</details>

## Actions 
- [x] Implementation is complete according to plan outlined in the RFC
- [x] Any necessary learning materials have been updated
- [x] The Ember team is ready to commit to the stability of
  any interfaces exposed by the current implementation of the feature 
- [x] Criteria for moving to Recommended Stage has been filled out
- [ ] Each [team](https://github.com/emberjs/rfcs#teams) has reviewed and approved

## Criteria for moving to Recommended (required)

A set of criteria for moving this RFC to the Recommended Stage, following release:

1. The stage of previously merged PRs back a reasonable amount of time has been verified and PRs to advance have been opened where necessary.

## Track Implementation

* [x] Write Blog Post (@kategengler): https://github.com/ember-learn/ember-blog/pull/1237
* [x] Update stages and release dates: #835
* [x] Update README and templates: #663
* [x] Merge https://github.com/ember-learn/ember-website/pull/972
* [x] Merge https://github.com/ember-learn/guides-source/pull/1863
* [x] Update rfcs.emberjs.com to handle stages correctly: https://github.com/ember-learn/rfcs-app/issues/10
* [x] Determine format for tracking these PRs in the frontmatter: #833
* [x] Automations for next stage PRs: #844

## Before Merge
* [ ] Merge #844.
  * [ ] make checks for newly opened RFCs required. They will pass on PRs that do not add an RFC.

## On Merge
* [ ] Publish Blog post: https://github.com/ember-learn/ember-blog/pull/1237
* [ ] Merge #663.
* [ ] Watch to see that a PR opened by the workflows added in #844 is opened to move this RFC to 'Released'

### CODE REVIEW

**Comment by kategengler** [comment]
Nice to haves: Labels for each stage PR, templates for each stage PR (especially Ready for Release with a section for a checklist for criteria for recommended).

**Comment by wagenet** [comment]
@wycats do you mean like what is in here https://github.com/emberjs/rfcs/pull/844?

**Comment by kategengler** [comment]
Pulling my reply from Discord:

The way we have designed it, stages has the same RFC move through and get modified along that way. Perhaps sections of the RFC that have instructions to be filled out by the time it gets to Recommended?
There are templates in the automation for the PRs that get opened. For example this is what a PR to recommended will look like when first opened https://github.com/kategengler/playground-ghas/pull/32

**Comment by wycats** [comment]
@kategengler makes sense to me! Mostly what I'm thinking about is that the process to go from stable to recommended requires an action plan, and I was wondering if there's an obvious way to incorporate that action plan into an existing step. 

I see that the [advance-to-ready-for-release.md](https://github.com/emberjs/rfcs/pull/844/files#diff-f826430af833f6afa2be53040899aaef84d3bd5f26364f86cc5a19fccdd76445) PR has "Criteria for moving to Recommended". Maybe we could copy the criteria into a draft [advance-to-recommended.md](https://github.com/emberjs/rfcs/pull/844/files#diff-b29b6f45a1855a787a60ebfb6cd67b63791cfd0eee6e1f5e22d573ec536bddc4) PR that would serve as a tracking issue and could be updated as the plan evolves?

**Comment by kategengler** [comment]
That is what I would imagine would happen -- the template for the draft `advance-to-recommended` PR (that will automatically open once the stage is advanced to released) mentions the criteria in the `Actions` todo list. It'd be nice to have the workflow automatically move the criteria between the PRs, but that would be a little tricky so I think for now leaving it to the person shepherding the PR to paste in those criteria (prompted by that Actions list) and evolve them is ok.

**Review by dfreeman — APPROVED** [review]
TypeScript Core is 👍

**Review by kategengler — APPROVED** [review]
Approving for CLI

**Review by ef4 — APPROVED** [review]
Approving for framework-core.

**Comment by jenweber** [comment]
The learning team meets on Monday, when we can do an official approval.

As the author of the RFC and an individual, this looks good to me!

**Review by jenweber — APPROVED** [review]
Approved for the Learning Team. We discussed it at today's meeting. Thanks all for moving this forward!

**Comment by runspired** [comment]
👋🏻 Approving for the Data team

I think labels as Katie suggested are probably the most useful thing to go with this RFC. Folks generally seem to scan the original RFC PRs and having the status label available is instant highly findable feedback. A little automation to go with those labels would be neat too but not required and since labels are pretty low overhead to create and apply this should be pretty easy for us to achieve.

**Review by runspired — APPROVED** [review]
👋🏻 Approving for the Data team

I think labels as Katie suggested are probably the most useful thing to go with this RFC. Folks generally seem to scan the original RFC PRs and having the status label available is instant highly findable feedback. A little automation to go with those labels would be neat too but not required and since labels are pretty low overhead to create and apply this should be pretty easy for us to achieve.

**Comment by kategengler** [comment]
The FCP has been completed! We will be merging and releasing stages now.

**Pull request merged**
