### PR TITLE
Convert Travis CI configuration into a GitHub Action

### PR DESCRIPTION
**Pull request by locks**
Successfully tested on [locks/rfcs](https://github.com/locks/rfcs/runs/1783587677) -> [github pages](https://locks.github.io/rfcs/).

### CODE REVIEW

**Review by kategengler — APPROVED** [review]

**Review by kategengler — CHANGES_REQUESTED** [review]
Try newer mdbook for security fixes

**Comment by NullVoxPopuli** [comment]
Is this still needed?

**Comment by kategengler** [comment]
Yes

**Comment by snewcomer** [comment]
This can be closed!

https://github.com/ember-cli/ember-cli/pull/9579

**Comment by rwjblue** [comment]
@snewcomer - This PR is to the RFCs repo itself, not RE: ember-cli blueprints...

**Review by kategengler — APPROVED** [review]

**Pull request merged**
