### PR TITLE
Contribution Guides

### PR DESCRIPTION
**Pull request by jessica-jordan**
[Rendered](https://github.com/jessica-jordan/rfcs/blob/contribute-to-ember/text/0446-contribution-guides.md)

### CODE REVIEW

**Comment by rwjblue** [comment]
Sounds awesome to me!

**Comment by MelSumner** [comment]
This is great work, thank you for making this idea happen! 👍

**Comment by kennethlarsen** [comment]
This is such a great idea - I'm really looking forward to this.

**Comment by jrjohnson** [comment]
Another possible source of inspiration https://www.nodetodo.org/

**Comment by MelSumner** [comment]
The Learning Core Team has reached consensus to move this to Final Comment Period.

**Comment by ppcano** [comment]
Recently, I have started to contribute more often and I have experienced some of the issues this RFC is improving. Love the idea and it would be very useful.

I will share some random feedback without going deeper into the details:

1 - Adding a section describing common type of welcome contributions:

- Small typos or correction: small PRs does not exist.

- Improve docs

- Search new issues on the Help wanted app.

- Specific areas: marketing, community...

- Jump into ongoing initiatives under the Status Board page.

- Help maintaining existing projects

- ...

2 - General tips for contributing from a newcomer’s perspective

This is likely already included on the `Topics` section, but I find interesting to describe more about general tips to focus not only on the first contribution but the long term.


Very good to help with "tips for the review process about finding a reviewer”. I think it also depends on the organization aspects of the community.

**Comment by jessica-jordan** [comment]
The Ember Learning Core team has reached consensus to merge this RFC and kick off the work for the Contribution Guides. A huge thank you goes to everyone who took the time to read and comment on the proposal! ✨

**Pull request merged**
