### PR TITLE
Move HTTP Mock to addon

### PR DESCRIPTION
**Pull request by mehulkar**
[rendered](https://github.com/mehulkar/rfcs/blob/http-mock/text/0000-http-mock.md)

### CODE REVIEW

**Comment by wagenet** [comment]
This seems reasonable to me. I'll see what I can do to get it moving.

**Comment by bertdeblock** [comment]
I've added this RFC to next week's agenda.

**Comment by runspired** [comment]
Moving to an addon seems great if doable; however, it would be better if we exposed a serverMiddleware hook directly to ember apps for this purpose. The dance otherwise is very complicated and not forward-thinking as we move away from older addon patterns. I'd like to see http-mocks be the default story, mirage is .... not an ideal solution for anyone.

**Comment by wagenet** [comment]
@runspired could you expand on this a bit. I'm guessing you'd suggest an ember-cli RFC for this change?

**Comment by runspired** [comment]
@wagenet currently to implement anything as a server-middleware it must be created as an addon. EmberCLI has no ability currently for sever middleware to be added except that mechanism. This makes creating solutions for apps that hook into the serve process very complicated: which includes any proposed http-mock replacement. Instead of mocks in-app you end up with mocks in an addon in the app.

**Comment by runspired** [comment]
Basically my suggestion is for embercli to add registerMiddleware to the EmberApp in ember-cli-build

**Comment by kategengler** [comment]
We think the medium-term plan should be to deprecate HTTP mock, rather than extract it. To that end, we are putting this in FCP to close.

**Pull request closed without merging**
