### PR TITLE
Query-Params Lifecycle

### PR DESCRIPTION
**Pull request by jamesarosen**
[Rendered](https://github.com/jamesarosen/rfcs/blob/qp-lifecycle/active/0000-qp-lifecycle.md)

### CODE REVIEW

**Comment by jamesarosen** [comment]
Related: emberjs/ember.js#9819, emberjs/ember.js#11592. 

See also http://stackoverflow.com/q/35192211/1190 (which works in an action handler, but not in a route hook like `afterModel`)

**Comment by jamesarosen** [comment]
I've done some monkey-patching to fix some of these things. In Ember 1.13, I had the following to ensure that all query-params were synced 
```js
// route:application
serializeQueryParam(value, key, ...args) {
  value = value || this.controllerFor('application').get(key);
  return this._super(value, key, ...args);
},

model() {
  const controller = this.controllerFor(this.routeName);
  controller.getWithDefault('queryParams', []).forEach(function(key) {
    if (controller.get(key) != null) return;
    controller.set(key, transition.queryParams[key]);
  });
}
```
But that broke on Ember 2.x due to emberjs/ember.js#11592. I changed the `model` hook to
```js
model(params, { queryParams }) {
  return queryParams;
},

afterModel(model, transition) {
  transition.send('fixQueryParams', transition.queryParams);
},

setupController(controller, model) {
  model = _.pick(model, [ 'valid', 'queryParams' ]);
  return this._super(controller, model);
},

actions: {
  fixQueryParams(queryParams) {
    let needsTransition = false;
    // do some munging of queryParams; if any munging, set needsTransition
    if (needsTransition) {
      Ember.run.next(this, 'replaceWith', { queryParams });
    }
  }
}
```
I couldn't do the `replaceWith({ queryParams })` in `afterModel` because it blew up with an error about `handlerInfos[handlerInfos.length - 1]` being `null`.

**Comment by knownasilya** [comment]
cc @nathanhammond

**Comment by rwjblue** [comment]
I think it is great to have this use case in mind and to start fleshing out what the constraints are, but this seems more like it belongs as an issue while we flesh it out into an actual concrete proposal.

Thoughts?

**Comment by jamesarosen** [comment]
> this seems more like it belongs as an issue

No objections. I'll reframe it as an issue on emberjs/ember.js and reference this RFC.

**Comment by jamesarosen** [comment]
Replacing with emberjs/ember.js#14785 for now.

**Pull request closed without merging**
