### PR TITLE
HTMLBars Component Attribute Types

### PR DESCRIPTION
**Pull request by zeppelin**
[Rendered](https://github.com/zeppelin/rfcs/blob/htmlbars-component-attribute-types/active/0000-htmlbars-component-attribute-types.md)

### CODE REVIEW

**Comment by mmun** [comment]
This should be fine. Given how the Handlebars parser works currently we can get `{{100}}` working but not `{{true}}`. I spoke with the Handlebars maintainer and he was OK with accepting a PR to accommodate the bool case.

**Comment by mixonic** [comment]
Oh man that is exiting.

**Comment by mmun** [comment]
This should be relatively straightforward to implement and will involve some minor changes to the Handlebars and HTMLBars parser. Anyone interested? cc @oneeman @marcioj

**Comment by marcioj** [comment]
@mmun I would like to help. I will try to send something in this weekend

**Comment by zeppelin** [comment]
So the resolution is to always use curlies ex. `attr={{true}}`?

I suspect this can cause some confusion, as people might wonder why `attr=false` is not working, not realizing they're in fact passing a string. Shouldn't there be at least a warning when attribute values are neither quoted, nor wrapped inside curlies?

**Comment by mmun** [comment]
@zeppelin Ah I misunderstood the proposal. I think a warning is a good idea for unquoted literal tokens. The alternative, to simply rewrite it to {{true}} at parse times, feels bad because it would mean change the semantics of HTML.

**Comment by zeppelin** [comment]
@mmun I'm fine with `{{true}}`. Even though it's slightly more ugly than just saying `true`, it's clear and unambiguous from Handlebars' perspective.

**Comment by jonathanKingston** [comment]
Shouldn't the meaning of an attribute come from the component definition rather than it's usage?

That way a component:
```
<my-element truthy="1" number="1" />
```
Could have the following attributes:
```
{truthy: true, number: 1}
```

That is more of the direction I was going with #35 that the JavaScript has precedence over the template usage. I'm happy to expand my idea to allow for types.

**Comment by mmun** [comment]
You can use `{{null}}`, `{{undefined}}`, `{{true}}`, `{{"foo"}}` (oh god why?!) and `{{3.14}}` now in HTMLBars. This should arrive in Ember in 1.13.

**Comment by jonathanKingston** [comment]
@mmun as I mentioned in #35 has there been any thought around using arrays within the dom? This is pretty much required to duplicate the behaviour of `link-to` helpers in a component (which there is many use-cases for this).

**Pull request closed without merging**
