### PR TITLE
[Data] Medium Term Plan

### PR DESCRIPTION
**Pull request by igorT**
[Rendered](https://github.com/igorT/rfcs/blob/igor/ember-data-medium-plan/text/0452-ember-data-medium-term-plan.md)

### CODE REVIEW

**Comment by mikkopaderes** [comment]
Not trying to be rude or anything and maybe it's just me not being able to fully absorb everything in this RFC. ✌️ 

Basically, my take is shouldn't the community just be concerned with the public APIs that'll be exposed to us? I feel the core team should be the one to decide how they want to design and structure their code base so long as they commit to the promised APIs and not break existing ones. There would be less overhead for the community to take in the RFC details and will let you guys (and other community members) to just dev immediately without waiting for our feedback.

**Comment by pete-the-pete** [comment]
Sounds good, and thanks for the diagrams!

The list of RFCs looks like a commitment to some ideas, which sounds good, but what does that mean for other RFCs? Can some be closed? Will others be folded in?

**Comment by igorT** [comment]
@mikkopaderes Your perspective makes a lot of sense, and I think in general internal refactors usually don't go through an RFC process. However given the size of the change, and the long term nature of the work, we felt that it made sense to have a place to lay out the plan and propose and debate the direction and align the contributors.. While not perfect, an RFC made sense for that.

**Comment by igorT** [comment]
@pete-the-pete Great point. This RFC spawned several new ones, and with regards to existing ones, we are going through them and addressing them, though most of them aren't impacted by these specific changes, other than the fact it should be easier to implement some of the RFC functionality in addons as opposed to ED core

**Pull request merged**
