### PR TITLE
`array` helper

### LINKED ISSUE #128: Add {{array ...}} helper
It seems it would be a perfect companion to the {{hash ...}} helper:

``` hbs
{{hash
  name="parent"
  children=(array
    (hash
      name="child1"
    )
    (hash
      name="child2"
    )
  )
}}
```

It would probably get the most use in component integration tests, but could be useful in normal templates as well. Taken from [here](https://github.com/kellyselden/ember-array-helper).

### PR DESCRIPTION
**Pull request by mmun**
[Rendered](https://github.com/emberjs/rfcs/blob/array-helper/text/0318-array-helper.md)

Closes #128.

### CODE REVIEW

**Comment by rwjblue** [comment]
:shipit: ❗️ ❤️

**Comment by mmun** [comment]
@kellyselden Damn! I should have checked first, sorry!

**Comment by kellyselden** [comment]
No worries. One less addon to maintain!

**Comment by ryanto** [comment]
Awesome, it would replace https://github.com/DockYard/ember-composable-helpers#array which we use in a lot of our apps.

**Comment by lukemelia** [comment]
Yes, please! It's unpleasantly surprising that Ember ships with a hash helper and not an array helper.

**Comment by tim-evans** [comment]
I've previously called the ones I've written `list`. Just an alternative name 😉

**Comment by mmun** [comment]
We discussed this at the core team meeting on 2018-03-30 and are ready to mark it for final comment period.

**Pull request merged**
