### PR TITLE
Allow {{mount}} syntax to accept parameters

### PR DESCRIPTION
**Pull request by mike183**
[Rendered](https://github.com/status200/rfcs/blob/ember-engines-mount-params/text/0000-ember-engines-mount-params.md)

### CODE REVIEW

**Comment by rwjblue** [comment]
👍 - Thanks for working on this (and the implementation PR https://github.com/emberjs/ember.js/pull/15174). The proposal seems good to me, but we should get @dgeb and @trentmwillis to weigh in on it from the Engines angle.

I'll add this to the Ember core team meeting agenda for this week also, to gather feedback from the group...

**Comment by dgeb** [comment]
@mike183 Thanks very much for working on this. I think this proposal aligns nicely with Ember as it stands today. This feature does not need to wait on framework-level decisions related to routes, controllers, and components, but can adapt as necessary when those decisions are made.

👍

**Comment by rwjblue** [comment]
We discussed this during todays Ember core team meeting today, and we are 👍 on this proposal.  

Given that there is little conversation here, and the proposal follows directly along with Ember's preexisting conventions we are moving this forward into the final comment period.

**Comment by ef4** [comment]
Can I do this?

```hbs
{{mount "my-engine" widget=(component "my-widget") }}
```

And if so, does that component properly close over the other components and helpers that it depends on, or will it try to find them inside the engine (and presumably fail)?

**Comment by rwjblue** [comment]
@ef4 - It should work properly (having access to things in the app but not in the engine), but we should add tests for that in the implementation PR.

**Comment by rwjblue** [comment]
@mike183 added a test to the implementation PR (https://github.com/emberjs/ember.js/pull/15174) confirming that @ef4's example does work properly.

The FCP has been going for 7 days, comments have been addressed and no new information has surfaced that would prevent us from landing this. I believe we are good to go here.

**Pull request merged**
