### PR TITLE
RFC: `network` Service

### PR DESCRIPTION
**Pull request by tomdale**
[Rendered](https://github.com/tomdale/rfcs/blob/network-service/text/0000-network-service.md)

### CODE REVIEW

**Comment by grapho** [comment]
This seems interesting. I am one of those users who, while learning, started with jquery-ajax and then _after_ it started to fail on me, switched to ic-ajax.  I have felt for a while that Ember should have its own simple built-in ajax-like function that actually fully works with RSVP.

**Comment by tomdale** [comment]
@praxxis points out some prior art: https://github.com/ember-cli/ember-ajax

**Comment by jcope2013** [comment]
throwing this discussion in here also, a con of fetch in my opinion is that fetch resolves successfully on 4xx and 5xx errors, but $.ajax rejects. https://github.com/ember-cli/rfcs/issues/19

**Comment by taras** [comment]
@tomdale you can see the discussion on this [`ember-cli/rcfs` PR that lead to `ember-ajax` being added to Ember CLI organization](https://github.com/ember-cli/rfcs/issues/19#issuecomment-137952616).

**Comment by mmun** [comment]
@jcope2013 I disagree that that is a con. The rejection state of a promise is only for exceptional cases (e.g. a network timeout). You should really think of it like a async try-catch construct.

**Comment by oriSomething** [comment]
i don't think it suppose to be in the core simply because many time as surprise it might sound, i don't use `ajax` / `fetch` in project and i'm sure may don't use either.
but anyway, `fetch` doesn't support `abort` because there is still no **cancelable promises**, so until `fetch` doesn't allow this option, `ajax` wrapper is still preferable

**Comment by stefanpenner** [comment]
For those interested in easily using fetch in ember apps today, checkout http://http://github.com/stefanpenner/ember-fetch

@tomdale. Maybe I missed it, but fetch and Ajax have different rejection semantics. Fetch does not reject on 500 rather it fulfills with a request object containing the status and errors. If we where to support fetch out of the box, without confusing people we may want to explore different defaults for the model hook. 

This confusion is actually why I didn't serious ember-Cli over to ember-fetch yet. In the rfc I opened, this ended up being a big community concern.

I suspect with some massaging the situation can be made much nice. And potentially nicer then what we have today.

**Comment by ilkkao** [comment]
It'd be nice to have a some kind of option to opt-out from this. For example in case the app communicates with server only through socket.io.

**Comment by stefanpenner** [comment]
> It'd be nice to have a some kind of option to opt-out from this. For example in case the app communicates with server only through socket.io.

thats covered in the proposal

**Comment by jonnii** [comment]
If bloat is a concern perhaps the `fetch` and `ajax` functionality can be split into two, with `fetch` shipping out of the box (and being the blessed path in guides etc..) and the ajax shim being an addon? FWIW I (personally) think there are enough compelling reasons to have a network service available in core.

**Comment by josemarluedke** [comment]
Github has a lib for the [fetch polyfill](https://github.com/github/fetch), maybe it's useable if is decided to implement this proposal.

**Comment by jamesarosen** [comment]
> throwing this discussion in here also, a con of fetch in my opinion is that fetch resolves successfully on 4xx and 5xx errors, but $.ajax rejects. -@jcope2013

> I disagree that that is a con. The rejection state of a promise is only for exceptional cases (e.g. a network timeout). You should really think of rejection an an async try-catch construct. -@mmun

One somewhat sane possibility would be to have `network.fetch` obey `fetch()` semantics and `network.ajax` obey `$.ajax` semantics.

**Comment by MiguelMadero** [comment]
@tomdale I share the concerns about the name conflicts. We already have a service and routing service. For routing is different and probably need the warnings or namespaces, but I'm wondering if this needs to be a service, since it doesn't hold to any state, can we just simply import it like `ic-ajax` today instead of "inject"ing it.

**Comment by Binarytales** [comment]
This RFC was pretty eye opening to me as someone who is relatively new to Ember. I have recently started using jQuery ajax where it sounds like I should be using `ic-ajax`.

It seemed odd to me that Ember did not already include this functionality in core.

I had a thought about addressing the size drawback but perhaps I'm not fully understanding how Ember depends on jQuery. However, my thought was, if Ember has an ajax "light" implementation in core then perhaps Ember could depend on a selective build of jQuery that does _not_ include it's full implementation of ajax. Instead jQuery's full ajax implementation could be the part that's available as an optional addon to developers that require it.

**Comment by tomdale** [comment]
For the moment, I'm retracting this RFC so that we can iterate a few ideas in the addon space. We're exploring whether the [ember-cli/ember-ajax addon](https://github.com/ember-cli/ember-ajax) can be used to solve the same set of problems without adding additional functionality to Ember core.

**Comment by tomdale** [comment]
Wrote up some of my thinking about how the addon ecosystem might look to address a similar issue: https://gist.github.com/tomdale/203ea125acd0be8b5f1f

**Pull request closed without merging**
