### PR TITLE
Deprecate hash helper

### PR DESCRIPTION
**Pull request by GreatWizard**
[Rendered](https://github.com/GreatWizard/rfcs/blob/hash-helper/text/0482-deprecate-hash.md)

### CODE REVIEW

**Comment by simonihmig** [comment]
I am not opposed to this, but given the vast amount of RFCs and changes and new concepts currently and over the past amount of months introduced as part of Octane and beyond, I am not sure this is the right time to introduce even more churn, in this case with relatively low value.

**Comment by buschtoens** [comment]
Good point. Can we maybe add `{{obj}}` without deprecating `{{hash}}` so that these who are "in on it" can write future-proof code already? Alternative would be writing a polyfill / add-on.

**Comment by chriskrycho** [comment]
Alternative perspective there: this is a relatively small (and trivially codemod-able) change, and landing it at the same time as we're updating/improving other helpers (`fn`, `on`, etc.) seems reasonable and even helpful to me.

**Comment by bendemboski** [comment]
Speaking for myself, I find `hash` more clear than `obj`. I don't doubt that `obj` will immediately make people think `object`, but `object` is such a generic term that means so many things in so many different contexts. Is it an EmberObject? A Javascript object? Some other type of object in the Ember/glimmer ecosystem that I haven't heard of?

By contrast, I think the term `hash` (or some variant of `hash table`) is pretty widely used across many programming languages to mean a set of key-value pairs. So while it can also mean a cryptographic hash, a hash function, a piece of a URL, or a culinary dish consisting of diced or chopped meat, potatoes and spices that are mixed together and cooked, I think it does a much better job of communicating what it does in context (i.e. when immediately followed by a list of assignments that are easily understood to be key/value pairs) than `obj` does.

So my personal vote would be for `hash` over `obj`.

However, perhaps we could consider `pojo` instead? That should immediately communicate what it's doing to pretty much any Javascript developer, and also has the advantage of being google-able, which `obj` (or `object`) and `hash` do too, but it's much harder to get to a clear/likely definition since they both mean multiple things.

**Comment by rwwagner90** [comment]
I personally do not think changing `hash` to `obj` is going to make things immediately clear to a developer who has never seen it before. With that in mind, we could assume the developer will go check the docs to see what the helper is doing, where they could read up on what `hash` is.

I would prefer to stick with `hash`, as it is familiar to Ember devs already, unless there is a strong case for changing it.

**Comment by jonnii** [comment]
I think if this was changed (which I wouldn't be for) it would also make sense to change the `RSVP.hash` method to match.

**Comment by chancancode** [comment]
See also: https://github.com/emberjs/rfcs/issues/473

@GreatWizard can you update the RFC to include renaming the helper parameters and the terminology in documentation

**Comment by joukevandermaas** [comment]
I agree with @rwwagner90 that `obj` is not clearer on the surface, but I could easily be convinced otherwise by some people who have trained Ember developers before and have some data/anecdotes.

In general I think just changing the name of something, without changing semantics, is not worth the effort. A bad name (and it is debatable whether `hash` is a bad name) will take a few minutes to get used to, but updating our apps may take many hours. A codemod would help but that will also take time and resources away from other Ember work.

**Comment by andreisebastianc-ccc** [comment]
> I agree with @rwwagner90 that `obj` is not clearer on the surface, but I could easily be convinced otherwise by some people who have trained Ember developers before and have some data/anecdotes.

I helped around 10 developers become productive with Ember and the `hash` helper was always straightforward. `yield` on the other hand, that's another story.

**Comment by GavinJoyce** [comment]
I don't think `hash` is a particularly a bad name, I personally haven't seen evidence of it being a confusing name with people new to Ember in my company. 

I also don't believe that `obj` is a good name, if we were to change `hash` I would prefer that we use `object` instead which I think it cleaner and avoids an unnecessary contraction.

**Comment by ondrejsevcik** [comment]
If this goes through, it should probably use longer name `object` rather than `obj` as there is already `array` helper and not `arr`.

**Comment by jenweber** [comment]
I do like the semantics of `obj` and I had no idea what `hash` was when I was first learning Ember. 

However, to add to some of the comments above, I think the google-ability is very important for new learners. If there are no other changes besides naming, I believe we should keep it as `hash`.

**Comment by locks** [comment]
@jonnii `RSVP` is a third-party library

**Comment by pzuraq** [comment]
> Speaking for myself, I find hash more clear than obj. I don't doubt that obj will immediately make people think object, but object is such a generic term that means so many things in so many different contexts. Is it an EmberObject? A Javascript object? Some other type of object in the Ember/glimmer ecosystem that I haven't heard of?

@bendemboski I think part of the confusion here is the idea that there could be any other type of object than a JavaScript object. There _shouldn't_ be more than one, and it should just be that - a POJO 😄 

I personally think this change would help to bring clarity as we start to move the ecosystem more in this direction. Once we can get rid of `EmberObject` and drop all the custom trappings of the old class model, the helper would _just_ be a direct analog to the only type of objects that we have to deal with - JavaScript objects.

That said, I do think the google-ability of hash is much higher, and `hash` is a term used for key-value stores frequently in other languages, so it's not a terrible term. I just think it actually adds more confusion for folks in the long run, since it'll be another term to teach, and an Ember-ism in general.

**Comment by pzuraq** [comment]
Another potential option here would be a true object literal syntax (alongside an array literal syntax). Curlies are out for that option, but some languages use double squares to represent objects:

```hbs
<button {{on 'click' (set this 'options' [[ key=value ]])}}></button>
```

**Comment by bendemboski** [comment]
@pzuraq I'd say yes and no. Even if EmberObjects go away, I still kinda doubt most non-advanced Javascript developers know that

```javascript
class Foo {}
typeof new Foo() === typeof {}
```

Even though I know that in the abstract, I tend to think of the two as very different use-case wise, even though they both end up being objects. Perhaps this is because I became experienced in several other languages before Javascript, and in most other languages whatever dictionary/associative array/hash thingy they provide is different from the thing you get when you instantiate a class.

I'm not a fan of the object literal syntax either -- more stuff that isn't google-able, and that would also force the consistency question of how to express arrays, causing some scope creep here.

As an aside, but one I've love to hear a response to, I'm still not understanding why we think this is a problem we need to solve. Do we have evidence that it's actually confusing people to any significant degree? I haven't heard an argument that this will make things better outside of what I judge to be speculative arguments based on prescriptive nomenclature, and with no evidence behind them, I have trouble seeing how they could win out over the google-ability argument.

**Comment by pzuraq** [comment]
I think the main thing is we're trying to remove Ember-isms and get as close to Just JavaScript™️ as we possibly can. `{{hash}}` sticks out because, well, there's nothing in JavaScript that is a hash. There are objects/POJOs, and there are `Map`s and `WeakMap`s and `Set`s and many other constructs, but vanilla JS doesn't have the concept of a hash, so we are definitely layering something on top here.

Personally I've actually typed out `obj` instead of `hash` before and been surprised, then remembered "oh right, we named it something completely different", more than once. I wouldn't be surprised if that doesn't come up more often than not, especially when `{{array}}` exists and _is_ a direct analog to a real thing in JavaScript.

**Comment by bendemboski** [comment]
@pzuraq what do you think of pojo? Seems Javascript-y, accurate, and google-able...

**Comment by pzuraq** [comment]
`{{pojo}}` feels a little bit more like JS, though it is industry slang so it could be hard for newcomers. It also has overlap/confusion with Java (Plain Old Java Object) which is where the term actually came from - I've gotten _very_ confused looks from Java devs when I start talking about POJOs in JavaScript. I think `{{hash}}` would be better than `{{pojo}}` tbh.
"Object" is a very overloaded term in general, but it _does_ have a specific meaning in each language it exists in. Every object-oriented language _must_ define what the term "object" means, usually quite explicitly, and it's the first thing new learners have to become familiar with. I'm personally not as worried about the use of the term because of this, even if it's overloaded in general.

**Comment by bendemboski** [comment]
> It also has overlap/confusion with Java (Plain Old Java Object)

True, but also [this](https://www.google.com/search?q=pojo+javascript) and [this](https://www.google.com/search?q=pojo+ember) (and of course the second would have Ember documentation hits after the change was made). And I don't think confused looks from *Java* devs are what we're worried about 😄 I suspect most developers that switched from Java to Javascript have encountered the term POJO and are quite comfortable with it in a Javascript context.

Anyway, I think maybe I'm starting to argue just to be right now, so I'm going to start disengaging.

**Comment by pzuraq** [comment]
Yeah, TBQH this is definitely major bikeshed territory (clearly 😛). One idea might be to include a couple different options for a while to actually see what works better here. When it comes to language/semantics design, I think at some point there are questions that just can't be answered directly, they need to be experimented with at large so that the users of the language can see what works most naturally (like how spoken languages evolve through slang and colloquialisms and such).

**Comment by bendemboski** [comment]
Agreed. Also, I think this conversation has gone on way too long without referencing [this](https://twitter.com/codinghorror/status/506010907021828096?lang=en) 😺

**Comment by 0xadada** [comment]
👎 bikeshedding only introduces more churn. Is the work to update the code, docs and asking developers to update hundreds/thousands of apps worth it, i think no.

**Comment by rtablada** [comment]
I'm personally not a big fan of renaming to obj.

While shorter and arguably cleaner I think it's a disservice for future to move to obj.
In terms of naming, JS objects are hashes (key value stores) but this is not the case in all languages.
With a future eye on WASM, Rust, etc the way we pass keys and references is much closer to `hash` in all languages vs `object` which can vary from language to language.

**Comment by rtablada** [comment]
For a clarifiction. IMO it would be a lot better to try to get a language level hashmap syntax as @pzuraq mentioned rather than shifting helpers around to try to address a bigger design issue.

**Comment by pzuraq** [comment]
As another data point here, I was introducing a friend who doesn't have a formal education and is new in general to programming to Ember. He currently uses a modified version of Dojo.js at his company, and he knows Vue and a bit of React. 

His first question when he saw the hash helper was "what's a hash?", and as I started explaining hash maps and dictionaries his eyes started glazing over. I said "it's an object" and he immediately got it, and we moved on. In my experience, this isn't uncommon for people who aren't familiar with programming terminology.

**Comment by mixonic** [comment]
In recent framework core conversations this problem space has come up. For reference

* https://github.com/emberjs/core-notes/blob/master/ember.js/2019-09/Meeting_Ember_Core_Team_20190920.md has a quick mention of my todo for this comment (but sorry no notes, it is hard to talk about a topic and be taking notes :-p)
* https://github.com/emberjs/core-notes/blob/master/ember.js/2019-09/F2F_Ember_Core_Team_20190914.md#literal-objectarray-notation from the recent F2F discusses a proposal for object and array literals in Ember templates. The gist is something like `{{hello (a=b)}}` and `{{hello [a.b c "hello"]}}`. There are a few interesting edge cases around exactly when the `(` for an object literal is required. This work is not in an RFC yet, but we certainly have consensus on core that some kind of literal is appropriate.

Given that we would like to introduce an syntax for objects, it doesn't seem very high value to change the name of the `(hash` helper. However there wasn't any push to FCP this RFC to close since there is agreement that the `(hash` helper *should* be deprecated (but for a literal syntax) and in general it seems like bad form to close RFCs which are superseded by something still only a pre-RFC proposal.

Thanks for raising this and for the discussion on this thread so far!

**Comment by GreatWizard** [comment]
Let's close it for now.

**Pull request closed without merging**
